server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://tech-app-backend.blacksea-9a4f48a0.swedencentral.azurecontainerapps.io/api/;
        proxy_set_header Host tech-app-backend.blacksea-9a4f48a0.swedencentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
    }
}