services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=3000
    env_file:
      - ./backend/.env

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend